comet_logger:
  initialize: true
  api_key: null
  project_name: null
  workspace: null
  name: null


training:
  epochs: 5
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  num_workers: 8
  optimizer: TODO
  loss: TODO

data:
  data_path: "/storage/homefs/tf24s166/code/cifar10/data"
  label_path: TODO
  target_column: target
  features: TODO

