hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True
comet_logger:
  initialize: true
  api_key: null
  project_name: null
  workspace: null
  name: null

early_stopping:
  initialize: true
  patience: 3
  min_delta: 0.001

training:
  epochs: 20
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  num_workers: 8
  optimizer: TODO
  loss: TODO

calibration:
  num_bins: 15

model:
  use_pretrained: false
  path_to_weights: '/storage/homefs/tf24s166/code/cifar10/outputs/2024-11-18/15-44-20/best_model.pth'

data:
  data_path: "/storage/homefs/tf24s166/code/classif_template/data"
  label_path: TODO
  targets: target
  features: TODO
  classif_type: multiclass10
