hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True
    
comet_logger:
  initialize: true
  api_key: null
  project_name: null
  workspace: null
  name: null

early_stopping:
  initialize: true
  patience: 12
  min_delta: 0.001

training:
  epochs: 100
  batch_size: 128
  learning_rate: 0.001
  weight_decay: 0.0001
  num_workers: 8
  optimizer: TODO
  loss: TODO

calibration:
  num_bins: 15

model:
  use_pretrained: false
  path_to_weights: None

data:
  data_path: "/storage/research/med_mlm/data/chexpertplus/chexpertplus/PNG/PNG/"
  label_path: "/storage/homefs/tf24s166/code/susu_split/{}_susu_chexpertplus.csv"
  targets: ['Edema'] #['Cardiomegaly','Edema', 'Consolidation', 'Pneumonia']
  features: TODO
  classif_type: chestxpert
